# Generated by Django 2.1.3 on 2018-11-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rank', models.IntegerField()),
                ('leader', models.CharField(max_length=100)),
                ('stat1', models.IntegerField()),
                ('stat2', models.IntegerField()),
            ],
        ),
    ]
