# Generated by Django 2.1.3 on 2018-12-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_delete_defense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rk', models.IntegerField()),
                ('team', models.CharField(max_length=25)),
                ('solo_tackles', models.IntegerField()),
                ('assisted_tackles', models.IntegerField()),
                ('total_tackles', models.IntegerField()),
                ('sacks', models.FloatField()),
                ('yards_lost_per_sack', models.IntegerField()),
                ('passes_defensed', models.IntegerField()),
                ('interceptions', models.IntegerField()),
                ('interception_return_yardage', models.IntegerField()),
                ('longest_interception_return', models.IntegerField()),
                ('interception_return_touchdowns', models.IntegerField()),
                ('forced_fumbles', models.IntegerField()),
                ('fumbles_recovered', models.IntegerField()),
                ('fumbles_returned_for_touchdowns', models.IntegerField()),
            ],
        ),
    ]
