# Generated by Django 2.1.3 on 2018-12-06 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_defense'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receiving',
        ),
    ]
