# Generated by Django 2.1.3 on 2018-12-06 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_delete_receiving'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('team', models.CharField(max_length=25)),
                ('receptions', models.IntegerField()),
                ('yards', models.IntegerField()),
                ('average', models.FloatField()),
                ('longest', models.IntegerField()),
                ('total_touchdowns', models.IntegerField()),
                ('longest_pass', models.IntegerField()),
                ('yards_per_game', models.FloatField()),
                ('fumbles', models.IntegerField()),
                ('fumbles_lost', models.IntegerField()),
            ],
        ),
    ]
