# Generated by Django 2.1.3 on 2018-12-06 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_receiving'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiving',
            name='longest_pass',
        ),
    ]
