# Generated by Django 2.1.3 on 2018-12-06 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_remove_receiving_longest_pass'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GiveTake',
            new_name='Turnovers',
        ),
    ]
