# Generated by Django 2.1.3 on 2018-12-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_auto_20181206_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='returning',
            name='longest_punts',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
